table DimDate
	lineageTag: 2eb28a20-fb3a-43aa-8742-73afb959543d
	dataCategory: Time

	column Date
		dataType: dateTime
		isKey
		formatString: Long Date
		lineageTag: aa5ff745-b7df-4f91-91dc-e8443ff12a4f
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 21a3bf4f-f1f3-46c6-abe3-b7eb29d24a73
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: int64
		formatString: 0
		lineageTag: e0b607fb-03b4-44f4-8155-34518a51e650
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column QuarterName
		dataType: string
		lineageTag: 959bea2d-398d-416f-a70f-6155a81a37bb
		summarizeBy: none
		sourceColumn: QuarterName

		annotation SummarizationSetBy = Automatic

	column MonthNum
		dataType: int64
		formatString: 0
		lineageTag: 4e56f501-0586-4153-89ef-7c07b5a4dd1c
		summarizeBy: none
		sourceColumn: MonthNum

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 00250bbb-d2d7-4d77-9480-dc881a8ac4d8
		summarizeBy: none
		sourceColumn: MonthName

		annotation SummarizationSetBy = Automatic

	column MonthShort
		dataType: string
		lineageTag: 8e632d1f-ba7b-4f9f-9df6-e4d1598ad6cf
		summarizeBy: none
		sourceColumn: MonthShort

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		formatString: 0
		lineageTag: c7692021-18b6-415b-aa95-7382e4f07a77
		summarizeBy: none
		sourceColumn: Day

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		formatString: 0
		lineageTag: f34b9a50-8186-4c40-80de-82ba48f19b79
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 26062f91-a6d3-44b2-a437-19c7f9b3e953
		summarizeBy: none
		sourceColumn: DayName

		annotation SummarizationSetBy = Automatic

	column DayShort
		dataType: string
		lineageTag: 49e306ff-67e5-4b72-a7f8-388ba1b177b9
		summarizeBy: none
		sourceColumn: DayShort

		annotation SummarizationSetBy = Automatic

	column YearMonth
		dataType: int64
		formatString: 0
		lineageTag: 796b7bed-1082-4534-b74d-9f7aba2741da
		summarizeBy: none
		sourceColumn: YearMonth

		annotation SummarizationSetBy = Automatic

	column YearMonthName
		dataType: string
		lineageTag: a6c4fa31-8c6d-4393-8c56-c2555b7e2dc7
		summarizeBy: none
		sourceColumn: YearMonthName

		annotation SummarizationSetBy = Automatic

	column IsWeekend
		dataType: string
		lineageTag: bab8fa65-8b3e-4d59-9d63-ce4fe8053fe5
		summarizeBy: none
		sourceColumn: IsWeekend

		annotation SummarizationSetBy = Automatic

	partition DimDate = m
		mode: import
		source =
				// Create new blank query, name it "DimDate"
				let
				    StartDate = #date(2011, 1, 1),
				    EndDate = #date(2014, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1,0,0,0)),
				    TableFromList = Table.FromList(DateList, Splitter.SplitByNothing()),
				    RenamedColumn = Table.RenameColumns(TableFromList,{{"Column1", "Date"}}),
				    ChangedType = Table.TransformColumnTypes(RenamedColumn,{{"Date", type date}}),
				
				    // Add calendar columns
				    AddYear = Table.AddColumn(ChangedType, "Year", each Date.Year([Date]), Int64.Type),
				    AddQuarter = Table.AddColumn(AddYear, "Quarter", each Date.QuarterOfYear([Date]), Int64.Type),
				    AddQuarterName = Table.AddColumn(AddQuarter, "QuarterName", each "Q" & Text.From([Quarter]), type text),
				    AddMonth = Table.AddColumn(AddQuarterName, "MonthNum", each Date.Month([Date]), Int64.Type),
				    AddMonthName = Table.AddColumn(AddMonth, "MonthName", each Date.MonthName([Date]), type text),
				    AddMonthShort = Table.AddColumn(AddMonthName, "MonthShort", each Text.Start([MonthName], 3), type text),
				    AddDay = Table.AddColumn(AddMonthShort, "Day", each Date.Day([Date]), Int64.Type),
				    AddDayOfWeek = Table.AddColumn(AddDay, "DayOfWeek", each Date.DayOfWeek([Date]) + 1, Int64.Type),
				    AddDayName = Table.AddColumn(AddDayOfWeek, "DayName", each Date.DayOfWeekName([Date]), type text),
				    AddDayShort = Table.AddColumn(AddDayName, "DayShort", each Text.Start([DayName], 3), type text),
				
				    // Add Year-Month for sorting
				    AddYearMonth = Table.AddColumn(AddDayShort, "YearMonth", each [Year] * 100 + [MonthNum], Int64.Type),
				    AddYearMonthName = Table.AddColumn(AddYearMonth, "YearMonthName", each Text.From([Year]) & "-" & [MonthShort], type text),
				
				    // Add IsWeekend flag
				    AddIsWeekend = Table.AddColumn(AddYearMonthName, "IsWeekend", each if [DayOfWeek] = 6 or [DayOfWeek] = 7 then "Weekend" else "Weekday", type text)
				in
				    AddIsWeekend

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

